# Generated by Django 2.2.12 on 2022-03-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id_postagem', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('nome_autor', models.CharField(max_length=50)),
                ('titulo_postagem', models.CharField(max_length=50)),
                ('data_postagem', models.DateTimeField(auto_now=True)),
                ('texto_postagem', models.TextField(max_length=500)),
            ],
        ),
    ]
