# Generated by Django 2.2.12 on 2022-03-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='id_postagem',
            field=models.AutoField(default=476359, max_length=6, primary_key=True, serialize=False),
        ),
    ]
