# Generated by Django 2.2.12 on 2022-03-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0002_auto_20220327_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='id_postagem',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
